version: '3.7'

x-env-variables: &env-variables
  NODE_ENV: development
  TERM: xterm-256color
  POSTGRES_USERNAME: postgres
  POSTGRES_PASSWORD: root
  RABBITMQ_HOST: rabbitmq

services:
  ### Start Product service ###
  product-service:
    command: sh -c "yarn && yarn dev"
    image: icommerce-product-service
    container_name: icommerce-product-service
    stdin_open: true
    tty: true
    environment:
      <<: *env-variables
      EXPRESS_PORT: 5000
      POSTGRES_DB_NAME: icommerce
      POSTGRES_HOST: product-service-postgres
    links:
      - product-service-postgres
      - rabbitmq
    ports:
      - 9229:9229
    volumes:
      - ./product-service:/product-service
    build:
      context: product-service
  product-service-postgres:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'icommerce'
    container_name: icommerce-product-service-postgres
  ### End Product service ###
  ### Start user activity service ###
  user-activity-service:
    command: sh -c "yarn && yarn dev"
    image: icommerce-user-activity-service
    container_name: icommerce-user-activity-service
    stdin_open: true
    tty: true
    environment:
      <<: *env-variables
      POSTGRES_DB_NAME: user-activities
      POSTGRES_HOST: user-activity-service-postgres
    links:
      - user-activity-service-postgres
      - rabbitmq
    ports:
      - 9230:9230
    volumes:
      - ./user-activity-service:/user-activity-service
    build:
      context: user-activity-service
  user-activity-service-postgres:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'user-activities'
    container_name: icommerce-user-activity-service-postgres
  ### End user activity service ###
  rabbitmq:
    image: rabbitmq:3.8.9-management-alpine
    container_name: icommerce-rabbitmq
    ports:
      - 15672:15672
  nginx:
    image: nginx:1.19.3
    container_name: icommerce-nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 8080:80
    environment:
      - NGINX_PORT=80

